// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRateLimitCache creates a new instance of MockRateLimitCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimitCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimitCache {
	mock := &MockRateLimitCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRateLimitCache is an autogenerated mock type for the RateLimitCache type
type MockRateLimitCache struct {
	mock.Mock
}

type MockRateLimitCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimitCache) EXPECT() *MockRateLimitCache_Expecter {
	return &MockRateLimitCache_Expecter{mock: &_m.Mock}
}

// Expire provides a mock function for the type MockRateLimitCache
func (_mock *MockRateLimitCache) Expire(ctx context.Context, key string, ttl time.Duration) (bool, error) {
	ret := _mock.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Expire")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, key, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRateLimitCache_Expire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expire'
type MockRateLimitCache_Expire_Call struct {
	*mock.Call
}

// Expire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *MockRateLimitCache_Expecter) Expire(ctx interface{}, key interface{}, ttl interface{}) *MockRateLimitCache_Expire_Call {
	return &MockRateLimitCache_Expire_Call{Call: _e.mock.On("Expire", ctx, key, ttl)}
}

func (_c *MockRateLimitCache_Expire_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *MockRateLimitCache_Expire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRateLimitCache_Expire_Call) Return(b bool, err error) *MockRateLimitCache_Expire_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRateLimitCache_Expire_Call) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration) (bool, error)) *MockRateLimitCache_Expire_Call {
	_c.Call.Return(run)
	return _c
}

// Incr provides a mock function for the type MockRateLimitCache
func (_mock *MockRateLimitCache) Incr(ctx context.Context, key string) (int64, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Incr")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRateLimitCache_Incr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Incr'
type MockRateLimitCache_Incr_Call struct {
	*mock.Call
}

// Incr is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRateLimitCache_Expecter) Incr(ctx interface{}, key interface{}) *MockRateLimitCache_Incr_Call {
	return &MockRateLimitCache_Incr_Call{Call: _e.mock.On("Incr", ctx, key)}
}

func (_c *MockRateLimitCache_Incr_Call) Run(run func(ctx context.Context, key string)) *MockRateLimitCache_Incr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRateLimitCache_Incr_Call) Return(n int64, err error) *MockRateLimitCache_Incr_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRateLimitCache_Incr_Call) RunAndReturn(run func(ctx context.Context, key string) (int64, error)) *MockRateLimitCache_Incr_Call {
	_c.Call.Return(run)
	return _c
}
